### ISSUE TITLE
[ERROR] [1652340319.334980863]: Unable to open port 

### ISSUE THREAD

**Issue by pvrohin** [garyservin/serial-example#2]
Hi

I have cloned this repository after installing the required serial library on (Ubuntu 20.04 ROS Noetic). However, even after specifying the correct port in the code and giving permissions to port using the command "sudo chmod a+rw /dev/tty/USB1", this error message is displayed. Any help would be appreciated !

**Comment by garyservin** [comment]
HI, you need to give permissions to your user to access the port and I've never used chmod to do that, you can try doing something like 
```
sudo usermod -a -G dialout $(whoami)
```
that command will add your user to the `dialout` group which can access the serial ports. You might need to logout and login again or restart your computer

**Comment by nowhereman1999** [comment]
> HI, you need to give permissions to your user to access the port and I've never used chmod to do that, you can try doing something like
> 
> ```
> sudo usermod -a -G dialout $(whoami)
> ```
> 
> that command will add your user to the `dialout` group which can access the serial ports. You might need to logout and login again or restart your computer

Hi,sorry to bother you here,but the error still exists even after I follow your advice to run the `sudo usermod -a -G dialout $(whoami)`:
![image](https://user-images.githubusercontent.com/53631206/221753182-d1245281-5755-48af-8832-a35f91d371d8.png)
so is there something else which caused this error,hope you can give me more suggestions!:-)

**Comment by garyservin** [comment]
@Hezhexi2002 you have to logout and login again or reboot your computer after adding your user to the group

**Comment by nowhereman1999** [comment]
> @Hezhexi2002 you have to logout and login again or reboot your computer after adding your user to the group

Sorry for not responding to you in time because I had class all day yesterday,I try to logout and login again and reboot but there is a new error like the picture below:
![image](https://user-images.githubusercontent.com/53631206/222094262-8da1adc3-0aae-4684-8c6d-b99c74483c57.png)
Is this due to the command `rosrun robot_serial robot_serial`  I used is wrong?but you haven't mentioned the way to run the node in README,so could you please give me some more information on how to run the node,I'd appreciated it if you can give me some advice!:-)

**Comment by garyservin** [comment]
Either you haven't build the package or your need to source your workspace. Please open a new ticket if you still have issues so we don't add more noise to this one. Thanks!

**Comment by nowhereman1999** [comment]
> Either you haven't build the package or your need to source your workspace. Please open a new ticket if you still have issues so we don't add more noise to this one. Thanks!

Ok,Thanks for your patient reply,I'm sure that I have successfully built the package and sourced the workspace but the problem doesn't disappear.Anyway,I've found a new code and am going to try to see if it works later.Sorry to bother you again under this closed issue.
